from app.constants.medical_constants import (
    MEDICAL_SKILLS,
    CERTIFICATION_KEYWORDS,
    LANGUAGES,
    LANGUAGE_PROFICIENCY_KEYWORDS,
    DEGREE_KEYWORDS,
    SPECIALIZATION_KEYWORDS,
    SKILL_SECTION_HEADERS,
    POSTGRADUATE_DEGREES,
    GRADUATE_DEGREES,
    SCHOOL_DEGREES,
)

__all__ = [
    "MEDICAL_SKILLS",
    "CERTIFICATION_KEYWORDS",
    "LANGUAGES",
    "LANGUAGE_PROFICIENCY_KEYWORDS",
    "DEGREE_KEYWORDS",
    "SPECIALIZATION_KEYWORDS",
    "SKILL_SECTION_HEADERS",
    "POSTGRADUATE_DEGREES",
    "GRADUATE_DEGREES",
    "SCHOOL_DEGREES",
]
